services:
  dev-db:
    image: postgres:17
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: video-conferencing-db
    networks:
      - videoConferencingApp
networks:
  videoConferencingApp: